version: '3.4'

services:
  back_offer:
    image: ${DOCKER_REGISTRY-}offer
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8083:80"
    networks:
      - mariadb_default

networks:
  mariadb_default:
    external: true
