version: '3.4'

services:
  back_candidate:
    image: ${DOCKER_REGISTRY-}candidate
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8081:80"
    networks:
      - mariadb_default

networks:
  mariadb_default:
    external: true
